name: Update README Table

on:
  push:
    branches: [ main ]

permissions:
  contents: write

# 동일 그룹의 워크플로우가 동시에 실행되지 않도록 설정
concurrency:
  group: update-readme
  cancel-in-progress: true

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Generate Table and Update README
        run: |
          chmod +x .github/scripts/update_readme.sh
          ./.github/scripts/update_readme.sh

      - name: Commit changes
        run: |
          git pull
          # README.md에 실제 변경사항이 있는지 체크
          if ! git diff --quiet HEAD -- README.md; then
            git add README.md
            git commit -m "Update README table automatically"
            git push
          else
            echo "No changes to commit"
          fi
